# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/main_window_exp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 387)
        MainWindow.setStyleSheet("/*#label {\n"
"    border-radius: 15px;\n"
"    padding: 4px;\n"
"    background-color: red;\n"
"}\n"
"*/\n"
"#input_image_text__f {\n"
"    color: white;\n"
"}\n"
"#upper_info_text__f {\n"
"    color: white;\n"
"}\n"
"#down_info_text__f {\n"
"    color: white;\n"
"}\n"
"#temperature_info_text__f  {\n"
"    color: white;\n"
"}\n"
"#decoder_info_text__f {\n"
"    color: white;\n"
"}\n"
"#screenshot_button__f {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(130, 62, 254, 255), stop:1 rgba(50, 59, 69, 255));\n"
"    border: 1 px white;\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"}\n"
"#load_button__f {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(130, 62, 254, 255), stop:1 rgba(50, 59, 69, 255));\n"
"    border: 1 px white;\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"}\n"
"#ocr_button__f {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 26, 52, 255), stop:1 rgba(205, 147, 84, 255));\n"
"    border: 1 px white;\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"}\n"
"#stop_ocr_button__s {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 26, 52, 255), stop:1 rgba(205, 147, 84, 255));\n"
"    border: 1 px white;\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"}\n"
"#back_button__s {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(130, 62, 254, 255), stop:1 rgba(50, 59, 69, 255));\n"
"    border: 1 px white;\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"}\n"
"#centralwidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(19, 23, 30, 255), stop:1 rgba(32, 40, 55, 255))\n"
"}\n"
"#decoder_combobox__f {\n"
"    border: 1px solid; border-radius:10px; background-color: palette(base); \n"
"}\n"
"#temp_slider_value__f {\n"
"    color: white;\n"
"}\n"
"#latex_label__s {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_image_text__f = QtWidgets.QLabel(self.centralwidget)
        self.input_image_text__f.setGeometry(QtCore.QRect(10, 5, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_image_text__f.setFont(font)
        self.input_image_text__f.setObjectName("input_image_text__f")
        self.input_image__f = QtWidgets.QLabel(self.centralwidget)
        self.input_image__f.setGeometry(QtCore.QRect(10, 150, 940, 110))
        self.input_image__f.setText("")
        self.input_image__f.setPixmap(QtGui.QPixmap("ui_files\\../ttt.png"))
        self.input_image__f.setObjectName("input_image__f")
        self.upper_info_text__f = QtWidgets.QLabel(self.centralwidget)
        self.upper_info_text__f.setGeometry(QtCore.QRect(500, 5, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.upper_info_text__f.setFont(font)
        self.upper_info_text__f.setObjectName("upper_info_text__f")
        self.down_info_text__f = QtWidgets.QLabel(self.centralwidget)
        self.down_info_text__f.setGeometry(QtCore.QRect(10, 30, 931, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.down_info_text__f.setFont(font)
        self.down_info_text__f.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.down_info_text__f.setTextFormat(QtCore.Qt.AutoText)
        self.down_info_text__f.setWordWrap(False)
        self.down_info_text__f.setObjectName("down_info_text__f")
        self.temperature_slider__f = QtWidgets.QSlider(self.centralwidget)
        self.temperature_slider__f.setGeometry(QtCore.QRect(10, 300, 160, 22))
        self.temperature_slider__f.setMinimum(1)
        self.temperature_slider__f.setSliderPosition(50)
        self.temperature_slider__f.setOrientation(QtCore.Qt.Horizontal)
        self.temperature_slider__f.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.temperature_slider__f.setObjectName("temperature_slider__f")
        self.temperature_info_text__f = QtWidgets.QLabel(self.centralwidget)
        self.temperature_info_text__f.setGeometry(QtCore.QRect(10, 260, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.temperature_info_text__f.setFont(font)
        self.temperature_info_text__f.setObjectName("temperature_info_text__f")
        self.decoder_info_text__f = QtWidgets.QLabel(self.centralwidget)
        self.decoder_info_text__f.setGeometry(QtCore.QRect(770, 260, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.decoder_info_text__f.setFont(font)
        self.decoder_info_text__f.setObjectName("decoder_info_text__f")
        self.decoder_combobox__f = QtWidgets.QComboBox(self.centralwidget)
        self.decoder_combobox__f.setGeometry(QtCore.QRect(740, 300, 202, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.decoder_combobox__f.setFont(font)
        self.decoder_combobox__f.setObjectName("decoder_combobox__f")
        self.decoder_combobox__f.addItem("")
        self.decoder_combobox__f.addItem("")
        self.screenshot_button__f = QtWidgets.QPushButton(self.centralwidget)
        self.screenshot_button__f.setGeometry(QtCore.QRect(10, 345, 260, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.screenshot_button__f.setFont(font)
        self.screenshot_button__f.setObjectName("screenshot_button__f")
        self.load_button__f = QtWidgets.QPushButton(self.centralwidget)
        self.load_button__f.setGeometry(QtCore.QRect(350, 345, 260, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_button__f.setFont(font)
        self.load_button__f.setObjectName("load_button__f")
        self.ocr_button__f = QtWidgets.QPushButton(self.centralwidget)
        self.ocr_button__f.setGeometry(QtCore.QRect(690, 345, 260, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.ocr_button__f.setFont(font)
        self.ocr_button__f.setObjectName("ocr_button__f")
        self.temp_slider_value__f = QtWidgets.QLabel(self.centralwidget)
        self.temp_slider_value__f.setGeometry(QtCore.QRect(180, 285, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.temp_slider_value__f.setFont(font)
        self.temp_slider_value__f.setObjectName("temp_slider_value__f")
        self.input_image__s = QtWidgets.QLabel(self.centralwidget)
        self.input_image__s.setGeometry(QtCore.QRect(970, 10, 940, 110))
        self.input_image__s.setText("")
        self.input_image__s.setPixmap(QtGui.QPixmap("ui_files\\../ttt.png"))
        self.input_image__s.setObjectName("input_image__s")
        self.splitter_line__s = QtWidgets.QFrame(self.centralwidget)
        self.splitter_line__s.setGeometry(QtCore.QRect(970, 120, 941, 16))
        self.splitter_line__s.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitter_line__s.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_line__s.setObjectName("splitter_line__s")
        self.back_button__s = QtWidgets.QPushButton(self.centralwidget)
        self.back_button__s.setGeometry(QtCore.QRect(970, 345, 260, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_button__s.setFont(font)
        self.back_button__s.setObjectName("back_button__s")
        self.stop_ocr_button__s = QtWidgets.QPushButton(self.centralwidget)
        self.stop_ocr_button__s.setGeometry(QtCore.QRect(1650, 345, 260, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.stop_ocr_button__s.setFont(font)
        self.stop_ocr_button__s.setObjectName("stop_ocr_button__s")
        self.latex_label__s = QtWidgets.QTextEdit(self.centralwidget)
        self.latex_label__s.setGeometry(QtCore.QRect(970, 149, 940, 180))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.latex_label__s.setFont(font)
        self.latex_label__s.setAutoFillBackground(False)
        self.latex_label__s.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.latex_label__s.setLineWidth(0)
        self.latex_label__s.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.latex_label__s.setReadOnly(True)
        self.latex_label__s.setObjectName("latex_label__s")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_image_text__f.setText(_translate("MainWindow", "La2eX"))
        self.upper_info_text__f.setText(_translate("MainWindow", "Загрузите изображение с диска или сделайте снимок экрана"))
        self.down_info_text__f.setText(_translate("MainWindow", "<html><head/><body><p style=\"line-height:0.5\">Инструкции:</p><p style=\"line-height:0.5\">1) Предельный размер сканируемой формулы - 940 на 110 пикселей</p><p style=\"line-height:0.5\">2) Сканируемое изображение должно содержать только фомулу и ничего лишнего</p><p>3) В случае ошибки сканирования, попробуйте измнеить параметры или изменить снимок﻿</p></body></html>"))
        self.temperature_info_text__f.setText(_translate("MainWindow", "Параметр температуры:"))
        self.decoder_info_text__f.setText(_translate("MainWindow", "Алгоритм распознавания:"))
        self.decoder_combobox__f.setItemText(0, _translate("MainWindow", "Жадный"))
        self.decoder_combobox__f.setItemText(1, _translate("MainWindow", "Лучевой"))
        self.screenshot_button__f.setText(_translate("MainWindow", "Снимок экрана"))
        self.load_button__f.setText(_translate("MainWindow", "Загрузить с диска"))
        self.ocr_button__f.setText(_translate("MainWindow", "Распознать"))
        self.temp_slider_value__f.setText(_translate("MainWindow", "50 %"))
        self.back_button__s.setText(_translate("MainWindow", "Вернуться в меню"))
        self.stop_ocr_button__s.setText(_translate("MainWindow", "Остановить распознавание"))
        self.latex_label__s.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
